
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 185
#define YY_END_OF_BUFFER 186
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[507] =
    {   0,
        0,    0,  186,  185,    1,  126,   80,  117,   39,  153,
      130,   54,  120,  137,   57,  114,   77,   74,    2,    3,
        4,    5,    6,    7,    8,    9,   10,   11,   56,  150,
      107,   85,  100,  143,   12,   13,   14,   15,   16,   17,
      185,   18,   19,   20,   21,   22,  131,   87,   55,  179,
       23,   24,   25,   26,   27,   28,  185,  185,   29,  185,
       30,  185,   31,   32,  185,   33,   34,   35,  185,   36,
      129,  133,   53,   58,  127,  119,   40,   41,  121,  139,
      138,  116,  115,   72,   78,    0,   75,  181,  182,  183,
      184,  149,  112,  108,   86,  101,  147,    0,  110,   88,

       89,   90,  180,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   76,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  103,    0,    0,  111,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  170,    0,
        0,    0,    0,    0,    0,  134,  135,   73,   82,  113,
      155,  148,    0,    0,   42,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   97,    0,    0,    0,
        0,  106,    0,    0,    0,    0,  124,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  166,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   43,
       44,    0,   46,    0,   48,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   83,   84,    0,
        0,    0,    0,    0,    0,    0,   99,    0,    0,  109,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      162,    0,    0,  165,    0,    0,    0,    0,    0,  175,
        0,    0,    0,    0,    0,   45,   47,    0,    0,    0,

       52,    0,    0,    0,    0,   60,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   94,   95,   96,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  151,    0,    0,    0,    0,    0,
        0,    0,  164,    0,    0,    0,  171,    0,  173,    0,
        0,    0,  178,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   71,
       79,    0,    0,   92,   93,   98,  104,  105,  118,    0,
        0,    0,    0,    0,    0,    0,    0,  142,    0,    0,
      146,  152,  154,  156,  159,  160,    0,    0,    0,  168,

        0,    0,    0,    0,    0,    0,   37,   38,    0,    0,
       51,    0,    0,    0,   59,    0,    0,    0,    0,    0,
        0,   70,    0,    0,  122,    0,    0,  128,    0,    0,
      140,    0,    0,    0,    0,    0,    0,  167,    0,    0,
      174,    0,  177,    0,   49,   50,   66,    0,   68,    0,
        0,    0,    0,   65,   69,    0,   91,    0,  125,  132,
      136,    0,    0,  145,    0,    0,  161,    0,  169,  172,
      176,    0,   67,    0,   61,   62,   63,    0,  123,  141,
        0,    0,    0,    0,  102,   64,    0,    0,    0,    0,
        0,    0,    0,    0,  158,    0,   81,    0,    0,  163,

        0,  157,    0,    0,  144,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    5,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,    1,   32,   33,   34,   35,   36,   37,
        1,    1,   38,    1,    1,   39,    1,   40,    1,   41,
        1,   42,    1,   43,   44,    1,    1,   45,    1,   46,
       47,   48,   49,   50,   51,    1,   52,   53,   54,   55,

       56,   57,   58,   59,   60,    1,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,   71,   72,   73,   74,
       75,   76,   77,   78,   79,   80,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[81] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[507] =
    {   0,
        0,    0,  512,  513,  513,  482,  513,  481,   75,  513,
      513,  513,  480,   71,  513,   72,   73,  479,   53,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  481,  513,
       60,  477,   61,  513,  513,  513,  513,  513,  513,  513,
      470,  465,  513,  513,  513,  513,  513,   40,  513,  474,
       34,   27,   56,   51,   35,   60,  437,   60,   48,   64,
       78,   65,   65,  445,   80,   86,   95,   81,   93,  513,
      513,  103,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  490,  513,  485,  513,  513,  513,  513,
      513,  513,  469,  467,  513,  513,  467,  459,  513,  513,

      513,  513,  513,  434,  430,  422,  426,  434,   24,  437,
      436,   87,  101,  416,  422,  416,  413,   78,  421,  418,
      416,  412,  419,  408,  513,  411,   95,  513,  412,  420,
      404,  410,  399,  415,  408,  413,  412,  102,  414,  106,
      401,   98,  116,  405,  401,  109,  100,  397,  513,  110,
      402,  393,  118,  401,  399,  513,  513,  513,  513,  513,
      513,  513,  418,  399,  513,  391,  393,  402,  397,  398,
      383,  381,  120,  128,  387,  396,  391,  393,  393,  388,
      380,  121,  386,  372,  388,  387,  513,  382,  372,  371,
      375,  513,  376,  362,  380,  375,  513,  356,  367,  360,

      359,  354,  355,  362,  359,  351,  350,  352,  355,  362,
      347,  345,  345,  348,  344,  129,  356,  513,  355,  345,
      349,  344,  337,  351,  353,  352,  341,  359,  337,  513,
      513,  339,  513,  340,  172,  329,  324,  340,  335,  338,
      323,  332,  321,  319,  319,  326,  324,  513,  513,  326,
      317,  316,  327,  320,  311,  316,  513,  311,  314,  513,
      315,  323,  306,  320,  307,  320,  303,  318,  313,  308,
      297,  306,  297,  294,  307,  297,  301,  306,  305,  296,
      513,  305,  283,  513,  144,  291,  296,  295,  281,  513,
      281,  282,  293,  310,  135,  513,  513,  325,  328,  294,

      513,  292,  273,  286,  275,  150,  276,  264,  276,  281,
      280,  275,  280,  263,  268,  513,  513,  513,  276,  260,
      273,  272,  265,  260,  269,  254,  253,  262,  251,  266,
      265,  262,  249,  252,  513,  260,  257,  259,  242,  252,
      258,  254,  513,  252,  252,  254,  513,  241,  513,  252,
      243,  251,  513,  264,  231,  242,  247,  246,  226,  235,
      223,  231,  222,  237,  118,  226,  218,  222,  217,  513,
      513,  232,  225,  513,  513,  513,  513,  513,  513,  228,
      231,  216,  213,  215,  224,  222,  207,  513,  208,  219,
      513,  513,  513,  223,  513,  513,  203,  221,  214,  513,

      207,  213,  206,  205,  196,  227,  513,  513,  194,  193,
      513,  192,  193,  205,  513,  207,  206,  191,  196,  199,
      198,  513,  202,  182,  513,  197,  180,  513,  181,  192,
      513,  191,  180,  176,  151,  188,  181,  513,  186,  186,
      513,  184,  513,  203,  513,  513,  513,  174,  513,  168,
      174,  167,  164,  513,  513,  179,  513,  176,  513,  513,
      513,  176,  162,  513,  160,  176,  513,  162,  513,  513,
      513,  184,  513,  155,  513,  513,  513,  172,  513,  513,
      167,  153,  152,  166,  513,  513,  150,  148,  161,  146,
      163,  144,  162,  144,  513,  149,  513,  155,  137,  513,

      150,  513,  124,   90,  513,  513
    } ;

static const flex_int16_t yy_def[507] =
    {   0,
      506,    1,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,    0
    } ;

static const flex_int16_t yy_nxt[594] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,    4,
       43,   44,    4,   45,    4,   46,   47,   48,   49,   50,
        4,   51,   52,   53,   54,   55,   56,   57,    4,   58,
        4,   59,   60,   61,   62,   63,    4,   64,   65,   66,
       67,   68,   69,    4,    4,   70,   71,   72,   73,   74,
       77,   80,   85,  100,   82,   88,   86,   93,   94,   96,
       97,  107,  169,  170,  108,  104,  116,   89,  117,   81,

       83,   84,  105,   78,  106,   90,  113,  109,  118,  128,
      101,  119,  129,  102,  110,  114,  125,  111,  149,  120,
      112,  121,  126,  127,  122,  115,   91,  123,  130,  132,
      136,  156,  138,  133,  131,  139,  137,  173,  141,  142,
      152,  145,  134,  182,  146,  153,  154,  183,  135,  143,
      174,  155,  144,  147,  175,  209,  191,  176,  150,  505,
      148,  202,  177,  151,  192,  205,  203,  211,  215,  220,
      217,  237,  206,  210,  218,  207,  216,  224,  221,  225,
      157,  240,  250,  212,  282,  251,  355,  238,  298,  417,
      299,  418,  504,  283,  239,  300,  241,  242,  344,  356,

      364,  503,  465,  345,  466,  365,  502,  346,  501,  366,
      500,  499,  498,  497,  496,  495,  494,  493,  492,  491,
      490,  489,  488,  487,  486,  485,  484,  483,  482,  481,
      480,  479,  478,  477,  476,  475,  474,  473,  472,  471,
      470,  469,  468,  467,  464,  463,  462,  461,  460,  459,
      458,  457,  456,  455,  454,  453,  452,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,

      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      363,  362,  361,  360,  359,  358,  357,  354,  353,  352,
      351,  350,  349,  348,  347,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,
      308,  307,  306,  305,  304,  303,  302,  301,  297,  296,

      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  249,  248,  247,  246,  245,  244,  243,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      223,  222,  219,  214,  213,  208,  204,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  190,  189,  188,  187,
      186,  185,  184,  181,  180,  179,  178,  172,  171,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,

      140,  124,  103,   99,   98,   95,   92,   87,   79,   76,
       75,  506,    3,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506

    } ;

static const flex_int16_t yy_chk[594] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        9,   14,   17,   48,   16,   19,   17,   31,   31,   33,
       33,   52,  109,  109,   52,   51,   55,   19,   55,   14,

       16,   16,   51,    9,   51,   19,   54,   53,   55,   59,
       48,   56,   59,   48,   53,   54,   58,   53,   67,   56,
       53,   56,   58,   58,   56,   54,   19,   56,   60,   61,
       62,   72,   63,   61,   60,   63,   62,  112,   65,   65,
       68,   66,   61,  118,   66,   68,   69,  118,   61,   65,
      112,   69,   65,   66,  113,  142,  127,  113,   67,  504,
       66,  138,  113,   67,  127,  140,  138,  143,  146,  150,
      147,  173,  140,  142,  147,  140,  146,  153,  150,  153,
       72,  174,  182,  143,  216,  182,  295,  173,  235,  365,
      235,  365,  503,  216,  173,  235,  174,  174,  285,  295,

      306,  501,  435,  285,  435,  306,  499,  285,  498,  306,
      496,  494,  493,  492,  491,  490,  489,  488,  487,  484,
      483,  482,  481,  478,  474,  472,  468,  466,  465,  463,
      462,  458,  456,  453,  452,  451,  450,  448,  444,  442,
      440,  439,  437,  436,  434,  433,  432,  430,  429,  427,
      426,  424,  423,  421,  420,  419,  418,  417,  416,  414,
      413,  412,  410,  409,  406,  405,  404,  403,  402,  401,
      399,  398,  397,  394,  390,  389,  387,  386,  385,  384,
      383,  382,  381,  380,  373,  372,  369,  368,  367,  366,
      364,  363,  362,  361,  360,  359,  358,  357,  356,  355,

      354,  352,  351,  350,  348,  346,  345,  344,  342,  341,
      340,  339,  338,  337,  336,  334,  333,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      305,  304,  303,  302,  300,  299,  298,  294,  293,  292,
      291,  289,  288,  287,  286,  283,  282,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  259,  258,  256,
      255,  254,  253,  252,  251,  250,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  234,  232,

      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      219,  217,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      196,  195,  194,  193,  191,  190,  189,  188,  186,  185,
      184,  183,  181,  180,  179,  178,  177,  176,  175,  172,
      171,  170,  169,  168,  167,  166,  164,  163,  155,  154,
      152,  151,  148,  145,  144,  141,  139,  137,  136,  135,
      134,  133,  132,  131,  130,  129,  126,  124,  123,  122,
      121,  120,  119,  117,  116,  115,  114,  111,  110,  108,
      107,  106,  105,  104,   98,   97,   94,   93,   86,   84,

       64,   57,   50,   42,   41,   32,   29,   18,   13,    8,
        6,    3,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 3 "scanner.l"
#include "cplusplus.h"
int lineno;
static int yywrap(void);
extern int yylex (void);
#line 748 "<stdout>"
#line 749 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 9 "scanner.l"

#line 968 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 507 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 513 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 10 "scanner.l"
{ ++lineno; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 12 "scanner.l"
{ return '0';}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 13 "scanner.l"
{ return '1';}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 14 "scanner.l"
{ return '2';}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 15 "scanner.l"
{ return '3';}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 16 "scanner.l"
{ return '4';}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 17 "scanner.l"
{ return '5';}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 18 "scanner.l"
{ return '6';}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 19 "scanner.l"
{ return '7';}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 20 "scanner.l"
{ return '8';}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 21 "scanner.l"
{ return '9';}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 22 "scanner.l"
{ return 'A';}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 23 "scanner.l"
{ return 'B';}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 24 "scanner.l"
{ return 'C';}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 25 "scanner.l"
{ return 'D';}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 26 "scanner.l"
{ return 'E';}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 27 "scanner.l"
{ return 'F';}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 28 "scanner.l"
{ return 'L';}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 29 "scanner.l"
{ return 'P';}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 30 "scanner.l"
{ return 'R';}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 31 "scanner.l"
{ return 'U';}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 32 "scanner.l"
{ return 'Z';}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 33 "scanner.l"
{ return 'a';}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 34 "scanner.l"
{ return 'b';}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 35 "scanner.l"
{ return 'c';}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 36 "scanner.l"
{ return 'd';}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 37 "scanner.l"
{ return 'e';}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 38 "scanner.l"
{ return 'f';}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 39 "scanner.l"
{ return 'l';}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 40 "scanner.l"
{ return 'n';}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 41 "scanner.l"
{ return 'p';}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 42 "scanner.l"
{ return 'r';}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 43 "scanner.l"
{ return 't';}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 44 "scanner.l"
{ return 'u';}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 45 "scanner.l"
{ return 'v';}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 46 "scanner.l"
{ return 'z';}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 47 "scanner.l"
{ return ALIGNAS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 48 "scanner.l"
{ return ALIGNOF;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 49 "scanner.l"
{ return AND;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 50 "scanner.l"
{ return AND_AND;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 51 "scanner.l"
{ return AND_EQ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 52 "scanner.l"
{ return ASM;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 53 "scanner.l"
{ return AUTO;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 54 "scanner.l"
{ return BOOL;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 55 "scanner.l"
{ return BREAK;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 56 "scanner.l"
{ return CASE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 57 "scanner.l"
{ return CATCH;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 58 "scanner.l"
{ return CHAR;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 59 "scanner.l"
{ return CHAR16_T;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 60 "scanner.l"
{ return CHAR32_T;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 61 "scanner.l"
{ return CHAR8_T;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 62 "scanner.l"
{ return CLASS;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 63 "scanner.l"
{ return CLOSE_BRACE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 64 "scanner.l"
{ return CLOSE_PAREN;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 65 "scanner.l"
{ return CLOSE_SQUARE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 66 "scanner.l"
{ return COLON;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 67 "scanner.l"
{ return COMMA;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 68 "scanner.l"
{ return COMPL;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 69 "scanner.l"
{ return CONCEPT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 70 "scanner.l"
{ return CONST;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 71 "scanner.l"
{ return CONSTEVAL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 72 "scanner.l"
{ return CONSTEXPR;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 73 "scanner.l"
{ return CONSTINIT;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 74 "scanner.l"
{ return CONST_CAST;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 75 "scanner.l"
{ return CONTINUE;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 76 "scanner.l"
{ return CO_AWAIT;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 77 "scanner.l"
{ return CO_RETURN;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 78 "scanner.l"
{ return CO_YIELD;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 79 "scanner.l"
{ return DECLTYPE;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 80 "scanner.l"
{ return DEFAULT;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 81 "scanner.l"
{ return DELETE;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 82 "scanner.l"
{ return DEREF;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 83 "scanner.l"
{ return DEREF_STAR;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 84 "scanner.l"
{ return DIV;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 85 "scanner.l"
{ return DIV_EQ;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 86 "scanner.l"
{ return DO;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 87 "scanner.l"
{ return DOT;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 88 "scanner.l"
{ return DOT_STAR;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 89 "scanner.l"
{ return DOUBLE;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 90 "scanner.l"
{ return DOUBLE_QUOTE;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 91 "scanner.l"
{ return DYNAMIC_CAST;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 92 "scanner.l"
{ return ELLIPSIS;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 93 "scanner.l"
{ return ELSE;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 94 "scanner.l"
{ return ENUM;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 95 "scanner.l"
{ return EQ;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 96 "scanner.l"
{ return EQ_EQ;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 97 "scanner.l"
{ return ESCAPE;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 98 "scanner.l"
{ return ESCAPE_HU;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 99 "scanner.l"
{ return ESCAPE_LU;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 100 "scanner.l"
{ return ESCAPE_LX;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 101 "scanner.l"
{ return EXPLICIT;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 102 "scanner.l"
{ return EXPORT;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 103 "scanner.l"
{ return EXTERN;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 104 "scanner.l"
{ return FALSE;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 105 "scanner.l"
{ return FINAL;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 106 "scanner.l"
{ return FLOAT;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 107 "scanner.l"
{ return FOR;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 108 "scanner.l"
{ return FRIEND;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 109 "scanner.l"
{ return GOTO;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 110 "scanner.l"
{ return GREATER;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 111 "scanner.l"
{ return GREATER_EQ;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 112 "scanner.l"
{ return IDENTIFIER;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 113 "scanner.l"
{ return IF;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 114 "scanner.l"
{ return IMPORT;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 115 "scanner.l"
{ return INLINE;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 116 "scanner.l"
{ return INT;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 117 "scanner.l"
{ return LESS;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 118 "scanner.l"
{ return LESS_EQ;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 119 "scanner.l"
{ return LONG;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 120 "scanner.l"
{ return LONG_LONG_H;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 121 "scanner.l"
{ return LONG_LONG_L;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 122 "scanner.l"
{ return LSHIFT;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 123 "scanner.l"
{ return LSHIFT_EQ;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 124 "scanner.l"
{ return MINUS;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 125 "scanner.l"
{ return MINUS_EQ;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 126 "scanner.l"
{ return MINUS_MINUS;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 127 "scanner.l"
{ return MOD;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 128 "scanner.l"
{ return MODULE;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 129 "scanner.l"
{ return MOD_EQ;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 130 "scanner.l"
{ return MULT;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 131 "scanner.l"
{ return MULT_EQ;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 132 "scanner.l"
{ return MUTABLE;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 133 "scanner.l"
{ return NAMESPACE;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 134 "scanner.l"
{ return NEW;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 135 "scanner.l"
{ return NOEXCEPT;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 136 "scanner.l"
{ return NOT;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 137 "scanner.l"
{ return NOT_EQ;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 138 "scanner.l"
{ return NULLPTR;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 139 "scanner.l"
{ return OPEN_BRACE;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 140 "scanner.l"
{ return OPEN_PAREN;}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 141 "scanner.l"
{ return OPEN_SQUARE;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 142 "scanner.l"
{ return OPERATOR;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 143 "scanner.l"
{ return OR;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 144 "scanner.l"
{ return OR_EQ;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 145 "scanner.l"
{ return OR_OR;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 146 "scanner.l"
{ return OVERRIDE;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 147 "scanner.l"
{ return PLUS;}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 148 "scanner.l"
{ return PLUS_EQ;}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 149 "scanner.l"
{ return PLUS_PLUS;}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 150 "scanner.l"
{ return PRIVATE;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 151 "scanner.l"
{ return PROTECTED;}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 152 "scanner.l"
{ return PUBLIC;}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 153 "scanner.l"
{ return QUERY;}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 154 "scanner.l"
{ return REINTERPRET_CAST;}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 155 "scanner.l"
{ return REQUIRES;}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 156 "scanner.l"
{ return RETURN;}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 157 "scanner.l"
{ return RSHIFT;}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 158 "scanner.l"
{ return RSHIFT_EQ;}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 159 "scanner.l"
{ return SCOPE;}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 160 "scanner.l"
{ return SEMICOLON;}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 161 "scanner.l"
{ return SHORT;}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 162 "scanner.l"
{ return SIGNED;}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 163 "scanner.l"
{ return SINGLE_QUOTE;}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 164 "scanner.l"
{ return SIZEOF;}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 165 "scanner.l"
{ return SPACESHIP;}
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 166 "scanner.l"
{ return STATIC;}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 167 "scanner.l"
{ return STATIC_ASSERT;}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 168 "scanner.l"
{ return STATIC_CAST;}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 169 "scanner.l"
{ return STRUCT;}
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 170 "scanner.l"
{ return SWITCH;}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 171 "scanner.l"
{ return TEMPLATE;}
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 172 "scanner.l"
{ return THIS;}
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 173 "scanner.l"
{ return THREAD_LOCAL;}
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 174 "scanner.l"
{ return THROW;}
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 175 "scanner.l"
{ return TRUE;}
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 176 "scanner.l"
{ return TRY;}
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 177 "scanner.l"
{ return TYPEDEF;}
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 178 "scanner.l"
{ return TYPEID;}
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 179 "scanner.l"
{ return TYPENAME;}
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 180 "scanner.l"
{ return UNICODE_8;}
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 181 "scanner.l"
{ return UNION;}
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 182 "scanner.l"
{ return UNSIGNED;}
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 183 "scanner.l"
{ return USING;}
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 184 "scanner.l"
{ return VIRTUAL;}
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 185 "scanner.l"
{ return VOID;}
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 186 "scanner.l"
{ return VOLATILE;}
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 187 "scanner.l"
{ return WCHAR_T;}
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 188 "scanner.l"
{ return WHILE;}
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 189 "scanner.l"
{ return XOR;}
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 190 "scanner.l"
{ return XOR_EQ;}
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 191 "scanner.l"
{ return ZERO_HB;}
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 192 "scanner.l"
{ return ZERO_HX;}
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 193 "scanner.l"
{ return ZERO_LB;}
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 194 "scanner.l"
{ return ZERO_LX;}
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 196 "scanner.l"
ECHO;
	YY_BREAK
#line 1951 "<stdout>"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 507 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 507 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 506);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 196 "scanner.l"

static int yywrap(void)
{
	return 1;
}


