test1:
	flex -t -d test1.l > test1.cpp
	g++ test1.cpp -o test1.exe
	./test1.exe test1.CPP
	
test2:
	flex -t -d test2.l > test2.cpp
	g++ -I. test2.cpp -o test2.exe
	./test2.exe test1.CPP

test3:
	flex -t -d test3.l > test3.cpp
	g++ -I. test3.cpp -o test3.exe
	./test3.exe	test3.CPP
test4:
	flex -t test4.l > test4.cpp
	g++ -I. test4.cpp -o test4.exe
	./test4.exe	test4.CPP	
test5:
	flex -t test5.l > test5.cpp
	g++ -I. test5.cpp -o test5.exe
	./test5.exe	test5.CPP
test6:
	flex -t test6.l > test6.cpp
	g++ -I. test6.cpp -o test6.exe
	./test6.exe	test6.CPP

test7:
	flex -t test7.l > test7.cpp
	g++ -I. test7.cpp -o test7.exe
	./test7.exe	test7.CPP		
	
test8:
	flex -t test8.l > test8.cpp
	g++ -I. test8.cpp -o test8.exe
	./test8.exe	test8.CPP		
test9:
	flex -t test9.l > test9.cpp
	g++ -I. test9.cpp -o test9.exe
	./test9.exe	test9.CPP		
	
test10:
	flex -t test10.l > test10.cpp
	g++ -I. test10.cpp -o test10.exe
	./test10.exe test10.CPP				
clean:
	rm -f *.exe		