
true is here
false
this is a raw-string R"delimit(I am inside raw-string a comment perhaps/*
a while space line next
false
true
R"another(this is ridiculous a inside one)another"
a while space line end
c-comment */)delimit";
here we have a wrong one
R"a invalid(inside an invalid delimiter)a invalid"
some other garbage
R"a_very-long-delimiter_and-hereistheone123-whyitissoimportantToHaveaLimited-lengthlimit?herewhy????(
now are we there yet
string str=R"delim(This is astring and 
new line \n "a quoted string"  'a single quote'
a tab \t and \n
a new line;
)delim"_escape;

bool is true and falsetrue
)a_very-long-delimiter_and-hereistheone123-whyitissoimportantToHaveaLimited-lengthlimit?herewhy????";
true is false
