this is a raw-string R"delimit(I am inside raw-string a comment perhaps/*
a while space line next

a while space line end
c-comment */)delimit";
"another ordiunary string literal"
some other garbage
dome	sdf"this is a ordinary string literal" outsie string literal
L"this is wide string literal"
qwu"u16 string literal"
wwu8"u8 string literal"
eeU"u32 string literal"
qu 8"is this an ordinary string literal?"
L"这是wide中文"
""
